# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b3e2829aee40128b80385065b36b5d0e8ea98582776ac54bb5c917f23bd789266631394b744e3668d2b750f84f5617bb13fd9eb4bf6e2d7bc61a4bd36a831570

test:
  secret_key_base: e0777ba6c735caa65192d67d2e1807a89b986fc2e4c03b740c85a232f727b501e76a65710b3f70279720c24b3c6b1040a152884768b29fbd3cac811738cf1495

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
